spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/code_vault
    username: jose
    password: joezhuspostgres
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

server:
  #端口号
  port: 8765

mybatis:
  type-handlers-package: com.aliersel.codevaultbackend.mapper.type_handler
  configuration:
    map-underscore-to-camel-case: true

security:
  jwt:
      token:
        secret-key: 3bb069b3d5feaa0146f8bb741bb9cb1389f729a8dc0152c3be5b756f079b55bc
        expire-length: 7200000

# 分页框架
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql