spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/db_example
    username: springuser
    password: ThePassword
    driver-class-name: org.postgresql.Driver
